//
// ArticlesAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

open class ArticlesAPI {

    /**
     News List
     
     - parameter q: (query) Theme of news 
     - parameter from: (query) date 
     - parameter sortBy: (query) Sort 
     - parameter language: (query) Language in two letters 
     - parameter apiKey: (query) API key 
     - parameter pageSize: (query) size of page (optional)
     - parameter page: (query) number of page (optional)
     - returns: ArticleList
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func everythingGet(q: String, from: String, sortBy: String, language: String, apiKey: String, pageSize: Int? = nil, page: Int? = nil) async throws -> ArticleList {
        return try await everythingGetWithRequestBuilder(q: q, from: from, sortBy: sortBy, language: language, apiKey: apiKey, pageSize: pageSize, page: page).execute().body
    }

    /**
     News List
     - GET /everything/
     - parameter q: (query) Theme of news 
     - parameter from: (query) date 
     - parameter sortBy: (query) Sort 
     - parameter language: (query) Language in two letters 
     - parameter apiKey: (query) API key 
     - parameter pageSize: (query) size of page (optional)
     - parameter page: (query) number of page (optional)
     - returns: RequestBuilder<ArticleList> 
     */
    open class func everythingGetWithRequestBuilder(q: String, from: String, sortBy: String, language: String, apiKey: String, pageSize: Int? = nil, page: Int? = nil) -> RequestBuilder<ArticleList> {
        let localVariablePath = "/everything/"
        let localVariableURLString = OpenAPIClientAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "q": (wrappedValue: q, isExplode: true),
            "from": (wrappedValue: from, isExplode: true),
            "sortBy": (wrappedValue: sortBy, isExplode: true),
            "language": (wrappedValue: language, isExplode: true),
            "apiKey": (wrappedValue: apiKey, isExplode: true),
            "pageSize": (wrappedValue: pageSize, isExplode: true),
            "page": (wrappedValue: page!, isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<ArticleList>.Type = OpenAPIClientAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false)
    }
}
